name: Build Stride Compiler

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Compiler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'  # Change this to the version that supports .NET 9.0

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release 

      - name: Build
        run: |
          dotnet publish ./Stride.CLI/Stride.CLI.csproj \
            -c Release \
            -r osx-arm64 \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:EnableCompressionInSingleFile=true \
            -o ./out/stride

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./out/stride